FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean

# Copy requirements FIRST to leverage Docker cache
COPY ./streamlit/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the entire streamlit app folder
COPY ./streamlit /app/streamlit

# Work inside the streamlit app
WORKDIR /app/streamlit

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
